accounts/urls.py
from django.urls import path
from accounts.views import login_user, logout_user, register_user
app_name = 'accounts'
urlpatterns = [
    path("login/", login_user, name='login'),
    path("register/", register_user, name='register'),
    path("logout/", logout_user, name='logout'),

]

students/urls.py
from django.urls import path
from students.views.func_based import (
    list_students,
    add_student,
    update_student,
    delete_student,
    detail_student
)
from students.views.class_based import (
    ListStudent,
    CreateStudent,
    StudentList,
    StudentDetail,
    UpdateStudent,
    DeleteStudent
)

# students
# students/add
app_name = 'students'
urlpatterns = [
    path("", list_students, name='list'),
    path("add/", add_student, name='add'),
    path("update/<int:pk>/", UpdateStudent.as_view(), name='update'),
    path("delete/<int:pk>/", DeleteStudent.as_view(), name='delete'),
    path("detail/<int:pk>/", StudentDetail.as_view(), name='detail'),

]

tnt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import HttpResponse
from students.views.func_based import welcome, home, about
from students.views.class_based import AddStudent
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from django.contrib import admin

urlpatterns = [
    path("", home),
    path('admin/', admin.site.urls),
    path("welcome/", welcome),
    path("students/", include("students.urls")),
    path("api/students/", include("students.urls_api")),
    path("accounts/", include("accounts.urls")),
    path("about/", AddStudent.as_view()),
    path("teams/", TemplateView.as_view(template_name='teams.html',
         extra_context={'title': 'TEAMS'})),
    path('api-auth/', include('rest_framework.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = "SHOP"

templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">{{title}}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'students:add' %}">Add Student</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/about/">About Us</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/admin/">Admin Panel</a>
          </li>
         
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
        {% if user.is_authenticated %}
        <span>Welcome {{user}}</span>
        <a href="{% url 'accounts:logout' %}" class="btn btn-danger">Logout</a>
        {% else %}
        <a href="{% url 'accounts:login' %}" class="btn btn-primary">Login</a>
        <a href="{% url 'accounts:register' %}" class="btn btn-info">Register</a>
        {% endif%}
      </div>
    </div>
  </nav>